WITH RankedData AS (
    SELECT 
        P.COD_TIT,
        A.CUSTOMER_ID,
        A.CRITERIO_CYBER,
        A.NUMERO_DOCUMENTO_CLIENTE,
        A.CODIGO_CLIENTE,
        A.DATA_ATIVACAO_CLIENTE,
        A.TIPO_PRODUTO,
        P.NUMERO_PARC,
        P.VR_ORIG_PARC,
        A.NUMERO_FATURA,
        ROW_NUMBER() OVER (PARTITION BY P.COD_TIT ORDER BY A.DATA_VENCIMENTO DESC) AS rn
    FROM PARCELAS P WITH (NOLOCK)
    INNER JOIN AUX_TIM_CYBER A WITH (NOLOCK) ON A.COD_PARC = P.COD_PARC
    WHERE P.DEVOLVIDO_PARC = '0'
)
SELECT 
    CAST(GETDATE() AS DATE) AS DATA,
    CAST(230 AS INT) AS ID_CRM, 
    CAST(
        CONCAT(
            RTRIM(CAST(D.CPFCGC_PES AS VARCHAR(20))), 
            RTRIM(CAST(REPLACE(A.CODIGO_CLIENTE, '.', '') AS VARCHAR(24)))
        ) AS VARCHAR(50)
    ) AS ID_CLI,
    CAST(D.CPFCGC_PES AS VARCHAR(20)) AS CPF,
    CAST(REPLACE(A.CODIGO_CLIENTE,'.','') AS NUMERIC(24,0)) AS DEVEDOR_ID,
    CAST(T.COD_DEV AS VARCHAR(20)) AS IDENTIFICADOR_ID,
    NULL AS TITULO_ID,
    CAST(T.CONTRATO_TIT AS VARCHAR(55)) AS CONTRATO_ID,
    CAST(A.NUMERO_DOCUMENTO_CLIENTE AS VARCHAR(65)) AS DOCUMENTO_ID,
    CAST(PE.NOME_PES AS VARCHAR(200)) AS NOME,
    CAST(CV.UF AS CHAR(2)) AS UF,
    CAST(CV.CIDADE AS VARCHAR(100)) AS CIDADE,
    CAST(PE.BAIRRO_PES AS VARCHAR(150)) AS BAIRRO,
    CAST(PE.CEP_PES AS VARCHAR(15)) AS CEP,
    CAST(PE.SEXO_PES AS CHAR(1)) AS SEXO,
    CAST(PE.DT_NASC AS DATETIME2) AS DATA_NASCIMENTO,
    CAST(NULL AS VARCHAR(25)) AS TIPO_TITULO,
    CAST(A.CRITERIO_CYBER AS VARCHAR(200)) AS SEGMENTO,
    --CAST(A.NUMERO_FATURA AS INT) AS NUMERO_PRESTACAO,
    NULL AS NUMERO_PRESTACAO,
    CAST(NULL AS INT) AS QTD_PRESTACAO,
    CAST(NULL AS VARCHAR(30)) AS NUMERO_BANCO,
    CAST(NULL AS VARCHAR(20)) AS SETOR,
    CAST(SP.TOTAL AS NUMERIC(15, 2)) AS VALOR,
    CAST(A.VR_ORIG_PARC AS NUMERIC(15, 2)) AS VALOR_ORIGINAL,
    CAST(NULL AS VARCHAR(30)) AS LOTE,
    CAST(SP.MENOR_VCTO AS DATETIME2) AS DATA_VENCIMENTO,
    CAST(NULL AS DATETIME2) AS DATA_VENCIMENTO_ORIGINAL,
    CAST(I.DATA_IMP AS DATETIME2) AS DATA_IMPORTACAO,
    CAST(NULL AS VARCHAR(720)) AS OBSE,
    CAST(NULL AS DATETIME2) AS DATA_DEVOLUCAO,
    CAST(A.DATA_ATIVACAO_CLIENTE AS DATETIME2) AS DATA_INCLUSAO,
    CAST(I.DATA_IMP AS DATETIME2) AS DATA_ALTERACAO,
    CAST(NULL AS VARCHAR(20)) AS USUARIO_INCLUSAO,
    CAST(NULL AS VARCHAR(20)) AS USUARIO_ALTERACAO,
    CAST(NULL AS VARCHAR(75)) AS IMP_ID,
    CAST(NULL AS VARCHAR(10)) AS ACORDO_ID,
    CAST(A.TIPO_PRODUTO AS VARCHAR(55)) AS TIPO_PRODUTO,
    CAST('52.179.19.141' AS VARCHAR(20)) AS INSTANCIA,
    CAST('MF_cobsystems' AS VARCHAR(20)) AS BANCO,
    CAST('VCOM' AS VARCHAR(30)) AS ORIGEM

FROM TITULOS T WITH (NOLOCK)
INNER JOIN _SOMA_PARC SP WITH (NOLOCK) ON SP.COD_TIT = T.COD_TIT
INNER JOIN v_devedores D WITH (NOLOCK) ON T.COD_DEV = D.COD_DEV
INNER JOIN RankedData A ON A.COD_TIT = T.COD_TIT AND A.rn = 1  -- FILTRANDO CTE
INNER JOIN (
  SELECT 
    H.COD_TIT,
    MAX(I.DATA_IMP) AS DATA_IMP
  FROM IMPORTACAO_HISTORICO H WITH (NOLOCK)
  INNER JOIN IMPORTACAO I WITH (NOLOCK) ON I.COD_IMP = H.COD_IMP
  WHERE H.COD_SITUACAO IN (1, 3, 4)
  GROUP BY H.COD_TIT
) I ON I.COD_TIT = T.COD_TIT
LEFT JOIN PESSOAS PE WITH (NOLOCK) ON D.COD_PES = PE.COD_PES
LEFT JOIN CV_PESSOAS_ENDERECOS CV WITH (NOLOCK) ON D.COD_PES = CV.COD_PES
WHERE CV.COD_STATE = 2;



