SELECT  R.DT_PGTO_REC AS DATA
	,230 AS COD_CRM
	,T.CONTRATO_TIT AS ID_ACORDO
	,VD.CPFCGC_PES AS ID_KEY
	,VF.NOME_FUNC AS USUARIO_PAGAMENTO
	,VF.NOME_FUNC AS OPERADOR
	,R.FORMA_PG_REC AS TIPO_PAGAMENTO
	,VPGTO.DES_PGTO AS TIPO_PAGAMENTO_NOME
	,R.VALOR_RECEBIDO_REC AS VALOR_PAGAMENTO
	,'52.179.19.141' AS INSTANCIA
	,'MF_cobsystems' AS BANCO
	,'VCOM' AS ORIGEM
FROM TITULOS T WITH (NOLOCK)
INNER JOIN RECEBIMENTOS R ON R.COD_TIT = T.COD_TIT
INNER JOIN v_devedores VD ON T.COD_DEV = VD.COD_DEV
INNER JOIN V_FUNCIONARIOS VF ON R.USUARIO_CAD = VF.COD_FUNC
INNER JOIN V_FORMA_PGTO VPGTO ON VPGTO.COD_PGTO = R.FORMA_PG_REC
ORDER BY 1 DESC