WITH PESSOAS_FONE AS (
    SELECT DISTINCT
        COD_PES AS CODIGO
    FROM PESSOAS_TELEFONES WITH (NOLOCK)
) 

SELECT
    B.DataProcessamento AS DATA,
    230 AS COD_CRM,
    NULL AS ID_ACORDO,
    PE.CPFCGC_PES AS ID_KEY,
    VF.NOME_FUNC AS USUARIO_ACORDO,
    B.DataVencimento AS DATA_VENCIMENTO_ORIGINAL,
    B.DataVencimento AS DATA_VENCIMENTO_ATUAL,
    CASE 
        WHEN TC.VR_ENTRADA <> 0 THEN TC.QTD_PARC + 1 
        ELSE TC.QTD_PARC 
    END AS QTD_PRESTACAO,
    B.ValorVencimento AS VALOR_ACORDO
FROM BOLETOS_EM B WITH (NOLOCK)
INNER JOIN BOLETOS_CALC BC ON BC.COD_BEM = B.Cod_BEm
INNER JOIN TITULOS_CALCULO TC ON TC.COD_TIT_CALC = BC.COD_TIT_CALC
INNER JOIN V_FUNCIONARIOS VF ON B.USUARIO_CAD = VF.COD_FUNC
INNER JOIN PESSOAS PE ON PE.COD_PES = (
    SELECT DISTINCT
        PESSOAS_FONE.CODIGO
    FROM PESSOAS_FONE
    WHERE PESSOAS_FONE.CODIGO = PE.COD_PES
)

WHERE CAST(B.DataProcessamento AS DATE) = CAST(GETDATE() AS DATE);

--WHERE B.DataProcessamento IS NOT NULL;
